apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.googlechat: spaceName
    notifications.argoproj.io/subscribe.on-deploy-succeeded.googlechat: spaceName
spec:
  project: default
  source:
    repoURL: https://github.com/JeremyArc/full-cicd-demonstration-project.git
    targetRevision: HEAD
    path: deployment/dummy-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
