apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  # Do not expose this url publicly , https://developers.google.com/workspace/chat/quickstart/webhooks#step_1_register_the_incoming_webhook
  space-webhook-url: https://chat.googleapis.com/v1/spaces/<space_id>/messages?key=<key>&token=<token>
